---
apiVersion: v2
description: Pyrsia Decentralized Package Network
name: pyrsia-node
appVersion: 0.2.0
version: 0.2.8
home: https://pyrsia.io
icon: https://raw.githubusercontent.com/pyrsia/pyrsia.github.io/main/static/img/icon-pyrsia-torch.svg
keywords: 
  - peer-to-peer
  - blockchain
  - decentralized
  - package-network
type: application
kubeVersion: "1.19.0-0 - 1.25.0-0"
