[package]
name = "blockchain"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = [ "lib" ]
name = "blockchain"
path = "src/blockchain.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
